global:
  scrape_interval: 15s

# scrape_configs:
#   - job_name: 'kafka'
#     static_configs:
#       - targets: ['kafka:9992']
scrape_configs:
  - job_name: 'kafka-1'
    static_configs:
      - targets: ['kafka-1:8686']
  - job_name: 'kafka-2'
    static_configs:
      - targets: ['kafka-2:8686']