global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-cluster'
    static_configs:
      - targets: 
          - 'kafka1:9992'
          - 'kafka2:9993'
          - 'kafka3:9994'
# //! Delete
    - job_name: 'kafka-consumers'
      static_configs:
        - targets:
          - 'kafka1:9992'
          - 'kafka2:9993'
          - 'kafka3:9994'